name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '.github/**' ]
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: |
            10.x.x
            9.x.x
            8.x.x
            7.x.x
            6.x.x
            5.x.x

      - name: apt-get for net5.0
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev          

      - name: Test
        run: |
          test()
          {
            local framework="$1"

            dotnet build --project ./sandbox -f "$framework"

            {
              echo "## $framework"
              echo
              echo '```'
              dotnet run \
                --project ./sandbox \
                -f "$framework" \
                --no-build \
                -c "${{ matrix.configuration }}"
              echo '```'
              echo
            } >> "$GITHUB_STEP_SUMMARY"
          }

          for framework in net10.0 net9.0 net8.0 net7.0 net6.0 net5.0; do
            test "$framework"
          done
