name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '.github/**' ]
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: |
            10.x.x
            9.x.x
            8.x.x
            7.x.x
            6.x.x
            5.x.x

      - name: Test
        run: |
          dotnet run --project ./sandbox  -f net10.0  -c ${{ matrix.configuration }}
          dotnet run --project ./sandbox  -f net9.0   -c ${{ matrix.configuration }}
          dotnet run --project ./sandbox  -f net8.0   -c ${{ matrix.configuration }}
          dotnet run --project ./sandbox  -f net7.0   -c ${{ matrix.configuration }}
          dotnet run --project ./sandbox  -f net6.0   -c ${{ matrix.configuration }}
          dotnet run --project ./sandbox  -f net5.0   -c ${{ matrix.configuration }}
